version: "3.4"
services:

  mongodb-sandbox:
    hostname: mongodb-sandbox
    build: ./
    restart: always
    links:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo

## Router
  mongo1:
    image: mongo
    container_name: mongo1
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27116:27017
    volumes:
      - ./scripts:/scripts
    networks:
      - mongo
  mongo2:
    image: mongo
    container_name: mongo2
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
    ports:
      - 27115:27017
    links:
      - mongo1
    networks:
      - mongo
  mongo3:
    image: mongo
    container_name: mongo3
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
    ports:
      - 27114:27017
    links:
      - mongo2
    networks:
      - mongo

## Config Servers
  configsvr01:
    image: mongo
    container_name: mongo-config-01
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
    ports:
      - 27119:27017
    links:
      - shard01-a
      - shard02-a
      - shard03-a
    networks:
      - mongo
  configsvr02:
    image: mongo
    container_name: mongo-config-02
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
    ports:
      - 27120:27017
    links:
      - configsvr01
    networks:
      - mongo
  configsvr03:
    image: mongo
    container_name: mongo-config-03
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
    ports:
      - 27121:27017
    links:
      - configsvr02
    networks:
      - mongo

## Shards
## Shards 01

  shard01-a:
    image: mongo
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27122:27017
    links:
      - shard01-b
      - shard01-c
    networks:
      - mongo
  shard01-b:
    image: mongo
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27123:27017
    networks:
      - mongo
  shard01-c:
    image: mongo
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27124:27017
    networks:
      - mongo

  ## Shards 02
  shard02-a:
    image: mongo
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27125:27017
    links:
      - shard02-b
      - shard02-c
    networks:
      - mongo
  shard02-b:
    image: mongo
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27126:27017
    networks:
      - mongo
  shard02-c:
    image: mongo
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27127:27017
    networks:
      - mongo

  ## Shards 03
  shard03-a:
    image: mongo
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
    ports:
      - 27128:27017
    links:
      - shard03-b
      - shard03-c
    networks:
      - mongo
  shard03-b:
    image: mongo
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
    ports:
      - 27129:27017
    networks:
      - mongo
  shard03-c:
    image: mongo
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
    ports:
      - 27130:27017
    networks:
      - mongo
networks:
  mongo: